//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaingEvents
    {
        public int eventId { get; set; }
        public string campaignName { get; set; }
        public string programName { get; set; }
        public string tacticName { get; set; }
        public string tacticStage { get; set; }
        public string ctaOffer { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public string theater { get; set; }
        public string subArea { get; set; }
        public string languages { get; set; }
        public string businessUnit { get; set; }
        public string businessSegment { get; set; }
        public string vertical { get; set; }
        public string targetAudience { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public string sfdcCampaignName { get; set; }
        public string sfdcDashboardLink { get; set; }
        public string promocode { get; set; }
        public string agencyInternal { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string programInitials { get; set; }
        public string linkLibrary { get; set; }
    }
}
