//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public int campaignId { get; set; }
        public string campaignName { get; set; }
    }
}
