//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class calawebEntities : DbContext
    {
        public calawebEntities()
            : base("name=calawebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<Campaigns> Campaigns { get; set; }
        public virtual DbSet<Programs> Programs { get; set; }
        public virtual DbSet<CampaingEvents> CampaingEvents { get; set; }
        public virtual DbSet<CalendarBlitz> CalendarBlitz { get; set; }
        public virtual DbSet<View_CalendarBlitz> View_CalendarBlitz { get; set; }
        public virtual DbSet<View_CalendarAll> View_CalendarAll { get; set; }
        public virtual DbSet<RA_managers> RA_managers { get; set; }
        public virtual DbSet<ViewCampaingEvents> ViewCampaingEvents { get; set; }
    }
}
