//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_managers
    {
        public int managerId { get; set; }
        public Nullable<int> regionId { get; set; }
        public Nullable<int> theaterId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public string title { get; set; }
        public string status { get; set; }
        public string email { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string survey { get; set; }
        public string acceptSurvey { get; set; }
        public string accessCampaignCalendar { get; set; }
    }
}
