//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CalendarBlitz
    {
        public int CampBlitzId { get; set; }
        public string CampBlitzName { get; set; }
        public string CampBlitzSFDCName { get; set; }
        public string CampBlitzSFDCLink { get; set; }
        public Nullable<System.DateTime> CampBlitzDateStart { get; set; }
        public string CampBlitzPartnerName { get; set; }
        public string CampBlitzTheater { get; set; }
        public string CampBlitzStatus { get; set; }
        public string CampBlitzFmm { get; set; }
        public string CampBlitzState { get; set; }
        public string dateStartString { get; set; }
        public string CampBlitzAgency { get; set; }
        public Nullable<System.DateTime> CampBlitzDateEnd { get; set; }
    }
}
