//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CalendarAll
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string SFDCName { get; set; }
        public string SFDCLink { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public string Theater { get; set; }
        public string Status { get; set; }
        public string TypeCalendar { get; set; }
        public int myId { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Agency { get; set; }
    }
}
